# Generated by Django 3.1.3 on 2021-04-09 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210409_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='R0000346', max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
