# Generated by Django 3.1.3 on 2021-04-27 08:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_case_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='case',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='part',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='part',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='part',
            name='recovery_dt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='oscillation_num',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='target',
            name='time_taken',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(max_length=50, null=True, verbose_name='Country'),
        ),
    ]
