# Generated by Django 3.1.3 on 2021-05-19 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210427_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='target',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
