# Generated by Django 3.1.3 on 2021-05-30 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210520_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='part_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='app.part'),
        ),
    ]
