# Generated by Django 3.1.3 on 2021-05-30 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210530_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
