# Generated by Django 3.1.3 on 2021-06-01 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210530_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictedrecovery',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
