# Generated by Django 3.1.3 on 2021-06-08 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210601_1142'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
