from .login_views import *
from .register_views import *
from .views import *
from .reset_password import *
from .profile_views import *
from .patients_views import *
from .case_views import *
from .part_views import *
from .exercise_views import *
from .residential_data_views import *